// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCML_lF3QG97D6u_LuonLiFlYWWyMeYTAk',
    appId: '1:138445630878:web:159c4e8576dd0565bfba8f',
    messagingSenderId: '138445630878',
    projectId: 'homework4-7915d',
    authDomain: 'homework4-7915d.firebaseapp.com',
    storageBucket: 'homework4-7915d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaIVXgXj2WCGsryKzsFnJtVPreAqu5H-A',
    appId: '1:138445630878:android:94e1d7a7a82aaad4bfba8f',
    messagingSenderId: '138445630878',
    projectId: 'homework4-7915d',
    storageBucket: 'homework4-7915d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoWXMPTq2FB3djPZBneOJb65Hw2n-LaBA',
    appId: '1:138445630878:ios:22efe669b3a25c3fbfba8f',
    messagingSenderId: '138445630878',
    projectId: 'homework4-7915d',
    storageBucket: 'homework4-7915d.appspot.com',
    iosBundleId: 'com.example.homew4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoWXMPTq2FB3djPZBneOJb65Hw2n-LaBA',
    appId: '1:138445630878:ios:90085d48c7536444bfba8f',
    messagingSenderId: '138445630878',
    projectId: 'homework4-7915d',
    storageBucket: 'homework4-7915d.appspot.com',
    iosBundleId: 'com.example.homew4.RunnerTests',
  );
}
